apiVersion: apps/v1
kind: Deployment
metadata:
  name: what-run-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: what-run-app
  template:
    metadata:
      labels:
        app: what-run-app
    spec:
      containers:
      - name: what-run-app
        image: what-run-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: what-run-app-service
spec:
  selector:
    app: what-run-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: what-run-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: what-run-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: what-run-app-service
            port:
              number: 80